"""Initial Migration

Revision ID: e8528392b4de
Revises: 
Create Date: 2020-10-02 11:23:48.155459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8528392b4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meals', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meals', 'menuday', ['menu_id'], ['id'])
    op.drop_constraint('menuday_meal_id_fkey', 'menuday', type_='foreignkey')
    op.drop_column('menuday', 'meal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuday', sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('menuday_meal_id_fkey', 'menuday', 'meals', ['meal_id'], ['id'])
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'menu_id')
    op.drop_table('orders')
    # ### end Alembic commands ###
